# Copyright 2018 Emil Dotchevski
# Copyright 2016 Peter Dimov
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

language: cpp

sudo: false

python: "2.7"

os:
  - linux
  - osx

branches:
  only:
    - master
    - develop

env:
  matrix:
    - BOGUS_JOB=true

addons:
  apt:
    packages:
      - g++-4.9
      - g++-5
      - g++-6
      - clang-3.6
      - clang-3.7
      - clang-3.8
      - ruby-full
      - ninja-build

    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
      - llvm-toolchain-precise-3.6
      - llvm-toolchain-precise-3.7
      - llvm-toolchain-precise-3.8

matrix:

  exclude:
    - env: BOGUS_JOB=true

  include:

    - os: linux
      env: DOC=1
      script:
        - |-
          echo "using asciidoctor ;" > ~/user-config.jam
        - ./b2 libs/leaf/doc
      deploy:
        local-dir: ../boost-root/libs/leaf/doc/html
        provider: pages
        skip-cleanup: true
        github-token: $GH_PAGES_TOKEN
        keep-history: false
        on:
          branch: master

    - os: osx
      compiler: clang++
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=11,14,1z

    - os: linux
      compiler: g++-4.9
      env: TOOLSET=gcc COMPILER=g++-4.9 CXXSTD=11
      addons:
        apt:
          packages:
            - g++-4.9
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      compiler: g++-5
      env: TOOLSET=gcc COMPILER=g++-5 CXXSTD=11,14,1z
      addons:
        apt:
          packages:
            - g++-5
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      compiler: g++-6
      env: TOOLSET=gcc COMPILER=g++-6 CXXSTD=11,14,1z
      addons:
        apt:
          packages:
            - g++-6
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      compiler: g++-7
      env: TOOLSET=gcc COMPILER=g++-7 CXXSTD=11,14,1z
      addons:
        apt:
          packages:
            - g++-7
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      compiler: g++-8
      env: TOOLSET=gcc COMPILER=g++-8 CXXSTD=11,14,17
      addons:
        apt:
          packages:
            - g++-8
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      compiler: /usr/bin/clang++
      env: TOOLSET=clang COMPILER=/usr/bin/clang++ CXXSTD=11
      addons:
        apt:
          packages:
            - clang-3.3

    - os: linux
      compiler: /usr/bin/clang++
      env: TOOLSET=clang COMPILER=/usr/bin/clang++ CXXSTD=11
      addons:
        apt:
          packages:
            - clang-3.4

    - os: linux
      compiler: clang++-3.5
      env: TOOLSET=clang COMPILER=clang++-3.5 CXXSTD=11,14,1z
      addons:
        apt:
          packages:
            - clang-3.5
            - libstdc++-4.9-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.5

    - os: linux
      compiler: clang++-3.6
      env: TOOLSET=clang COMPILER=clang++-3.6 CXXSTD=11,14,1z
      addons:
        apt:
          packages:
            - clang-3.6
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6

    - os: linux
      compiler: clang++-3.7
      env: TOOLSET=clang COMPILER=clang++-3.7 CXXSTD=11,14,1z
      addons:
        apt:
          packages:
            - clang-3.7
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7

    - os: linux
      compiler: clang++-3.8
      env: TOOLSET=clang COMPILER=clang++-3.8 CXXSTD=11,14,1z
      addons:
        apt:
          packages:
            - clang-3.8
            - libstdc++-4.9-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8

    - os: linux
      compiler: clang++-3.9
      env: TOOLSET=clang COMPILER=clang++-3.9 CXXSTD=11,14,1z
      addons:
        apt:
          packages:
            - clang-3.9
            - libstdc++-4.9-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9

    - os: linux
      compiler: clang++-4.0
      env: TOOLSET=clang COMPILER=clang++-4.0 CXXSTD=11,14,1z
      addons:
        apt:
          packages:
            - clang-4.0
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0

    - os: linux
      compiler: clang++-5.0
      env: TOOLSET=clang COMPILER=clang++-5.0 CXXSTD=11,14,1z
      addons:
        apt:
          packages:
            - clang-5.0
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0

    - os: linux
      compiler: clang++-6.0
      env: TOOLSET=clang COMPILER=clang++-6.0 CXXSTD=11,14,17
      addons:
        apt:
          packages:
            - clang-6.0
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0

install:
  - gem install asciidoctor
  - gem install coderay
  - pip3 install meson
  - cd ..
  - git clone -b $TRAVIS_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule update --init tools/build
  - git submodule update --init tools/inspect
  - git submodule update --init libs/config
  - git submodule update --init tools/boostdep
  - mkdir libs/leaf
  - cp -r $TRAVIS_BUILD_DIR/* libs/leaf
  - python tools/boostdep/depinst/depinst.py leaf -I example
  - ./bootstrap.sh
  - ./b2 headers
  - cd libs/leaf
  - meson bld/debug

script:
  - |-
    echo "using $TOOLSET : : $COMPILER ;" > ~/user-config.jam
  - ./b2 variant=debug test toolset=$TOOLSET cxxstd=$CXXSTD
  - ./b2 variant=release test toolset=$TOOLSET cxxstd=$CXXSTD
  - cd bld/debug && meson test

notifications:
  email:
    on_success: always
